// Full_Stack/frontend/src/components/TaskForm.tsx
import React, { useState } from 'react';
import type { CreateTaskRequest } from '../types';

interface TaskFormProps {
  onSubmit: (task: CreateTaskRequest) => void;
}

export const TaskForm: React.FC<TaskFormProps> = ({ onSubmit }) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;
    onSubmit({ title, description });
    setTitle('');
    setDescription('');
  };

  return (
    <form onSubmit={handleSubmit} className="mb-8 bg-white p-6 rounded-xl shadow-md border border-gray-100">
      <div className="grid grid-cols-1 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Task Title</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="What needs to be done?"
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Description (Optional)</label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Add more details..."
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
            rows={3}
          />
        </div>
        <button
          type="submit"
          className="w-full py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors shadow-sm"
        >
          Add Task
        </button>
      </div>
    </form>
  );
};

// Java/frontend/src/app/components/task-form/task-form.component.ts
import { Component } from '@angular/core';
import { TaskService } from '../../services/task.service';
import { Task } from '../../models/task.model';
import { EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-task-form',
  standalone: true,
  imports: [],
  template: `
    <form (submit)="onSubmit($event)" class="flex flex-col sm:flex-row gap-3">
      <input
        #titleInput
        type="text"
        placeholder="What needs to be done?"
        class="flex-1 p-3 border border-gray-200 rounded-xl shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
        required>
      <button
        type="submit"
        class="bg-blue-600 text-white px-6 py-3 rounded-xl font-semibold hover:bg-blue-700 active:scale-95 transition-all shadow-md hover:shadow-lg">
        Add Task
      </button>
    </form>
  `
})
export class TaskFormComponent {
  @Output() taskAdded = new EventEmitter<void>();

  constructor(private taskService: TaskService) {}

  onSubmit(event: Event): void {
    event.preventDefault();
    const input = event.target as HTMLFormElement;
    const title = (input.querySelector('input') as HTMLInputElement).value;

    const newTask: Task = {
      title: title,
      description: '',
      completed: false
    };

    this.taskService.createTask(newTask).subscribe(() => {
      this.taskAdded.emit();
      (input.querySelector('input') as HTMLInputElement).value = '';
    });
  }
}
