// Full_Stack/frontend/src/components/TaskItem.tsx
import React from 'react';
import type { Task } from '../types';

interface TaskItemProps {
  task: Task;
  onToggle: (id: number) => void;
  onDelete: (id: number) => void;
}

export const TaskItem: React.FC<TaskItemProps> = ({ task, onToggle, onDelete }) => {
  return (
    <div className="flex items-center justify-between p-4 mb-3 bg-white rounded-lg shadow-sm border border-gray-200 hover:border-blue-300 transition-colors">
      <div className="flex items-center gap-4">
        <input
          type="checkbox"
          checked={task.completed}
          onChange={() => onToggle(task.id)}
          className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500 cursor-pointer"
        />
        <div>
          <h3 className={`font-medium ${task.completed ? 'line-through text-gray-400' : 'text-gray-800'}`}>
            {task.title}
          </h3>
          {task.description && <p className="text-sm text-gray-500">{task.description}</p>}
        </div>
      </div>
      <button
        onClick={() => onDelete(task.id)}
        className="text-red-500 hover:text-red-700 p-2 hover:bg-red-50 rounded-full transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fillRule="evenodd" d="M9 2a1 1 0 00-1 1v11a1 1 0 102 0V3a1 1 0 00-1-1zm4 0a1 1 0 00-1 1v11a1 1 0 102 0V3a1 1 0 00-1-1z" clipRule="evenodd" />
        </svg>
      </button>
    </div>
  );
};

// Java/frontend/src/app/components/task-item/task-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Task } from '../../models/task.model';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-task-item',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex items-center justify-between p-4 bg-white rounded-lg shadow border border-gray-200">
      <div class="flex items-center gap-3">
        <input
          type="checkbox"
          [checked]="task.completed"
          (change)="onToggle.emit()"
          class="w-5 h-5 cursor-pointer">
        <span [class.line-through]="task.completed" class="text-lg text-gray-700">
          {{ task.title }}
        </span>
      </div>
      <button
        (click)="onDelete.emit()"
        class="text-red-500 hover:text-red-700 font-medium">
        Delete
      </button>
    </div>
  `
})
export class TaskItemComponent {
  @Input() task!: Task;
  @Output() onToggle = new EventEmitter<void>();
  @Output() onDelete = new EventEmitter<void>();
}
